文档彩色字修正
LNSSPsd/PhoenixBuilder pull request #111
Opened 2022-10-24 12:57 UTC by Inotart

插件部分的文档 没彩色纸,搬运的时候顺便修正

2022-10-24 14:24 UTC, Inotart commented
添加了引擎帮助文档的完全汉化

2022-11-07 06:55 UTC, LNSSPsd commented on doc/script_engine_cn/全局函数.md
> +将消息进行格式化并以输出到  `stdout` **(没有换行符)**
将消息进行格式化  
**并以**  
输出到
^
Invalid sentence

2022-11-07 06:55 UTC, Inotart commented
你好,我目前不在，如果你只是看到论坛邮件就不用回复了

2022-11-07 06:56 UTC, LNSSPsd commented on doc/script_engine_cn/常数.md
> +# 常数
可能 `常量` 更好？

2022-11-07 06:57 UTC, LNSSPsd commented on doc/script_engine_cn/常数.md
> +当前运行的服务器号
```suggestion
当前的服务器号
```

2022-11-07 06:57 UTC, LNSSPsd commented on doc/script_engine_cn/常数.md
> +# 常数
```suggestion
# 常量
```

2022-11-07 06:58 UTC, LNSSPsd commented on doc/script_engine_cn/引擎.md
> +**警告：对于脚本包，不应调用此名称，因为名称将自动设置**
```suggestion
**警告：对于脚本包，不应调用此名称，因为名称会被自动设置**
```

2022-11-07 07:01 UTC, LNSSPsd commented on doc/script_engine_cn/引擎.md
> +显示名称将作为脚本输出的前缀附加到用户。
```suggestion
面向用户的输出会以此显示名作为前缀。
```

2022-11-07 07:01 UTC, LNSSPsd commented on doc/script_engine_cn/引擎.md
> +等到与游戏的连接建立。
```suggestion
等待连接建立。
```

2022-11-07 07:04 UTC, LNSSPsd reviewed
Please reconsider your translations.

2022-11-07 17:32 UTC, Inotart commented
已针对上述的翻译问题做出了修复

2022-11-08 00:57 UTC, LNSSPsd commented on doc/script_engine_cn/游戏.md
> +**警告:如果执行的指令没有对应的相应,那么此命令将会导致代码堵塞无法继续运行**
```suggestion
**警告:如果执行的指令没有对应的响应,那么此命令将会导致代码堵塞无法继续运行**
```

2022-11-08 00:59 UTC, LNSSPsd commented on doc/script_engine_cn/游戏.md
> +* `response` `<Object>`
```suggestion
** `response` `<Object>`
```

2022-11-08 01:00 UTC, LNSSPsd commented on doc/script_engine_cn/游戏.md
> +如果没有 `callback` ,则与  [game.oneShotCommand](game.md#gameoneshotcommandcommand)  相同
```suggestion
如果没有指定 `callback` ,则与  [game.oneShotCommand](game.md#gameoneshotcommandcommand)  相同
```

2022-11-08 01:00 UTC, LNSSPsd commented on doc/script_engine_cn/游戏.md
> +* `packet` `<Object>`
```suggestion
** `packet` `<Object>`
```

2022-11-08 01:01 UTC, LNSSPsd commented on doc/script_engine_cn/游戏.md
> +* `message` `<string>`
```suggestion
** `name` `<string>`
** `message` `<string>`
```

2022-11-08 01:02 UTC, LNSSPsd reviewed
There are still some small problems with the translation or markdown format.
Please fix them and this pr will be accepted.

2022-11-09 04:46 UTC, LNSSPsd requested changes
```
- * packet
+ ** packet
```

2022-11-09 05:58 UTC, Inotart commented
> ```
> - * packet
> + ** packet
> ```

已修改,
建议表示 加粗的可选参数 用 * * 表示
例如上述

> ```
> - * packet
> + * *packet
> ```
这样子不会出现文档的渲染问题

2022-11-09 06:26 UTC, LNSSPsd requested changes
![2319A5EC-C15C-4EE1-A8C7-FCB2431416B2](https://user-images.githubusercontent.com/24724395/200755402-0aeeee78-4807-4de1-a931-09849f6b87f0.png)
Well, it got messed up :(

2022-11-09 06:28 UTC, LNSSPsd commented
And what's more, no second leveled list for return values. That stuff is only for things like arguments for a callback, instead of regular return.

2022-11-09 06:46 UTC, Inotart commented
> 更重要的是，返回值没有第二个分级列表。这些东西仅用于回调的参数之类的东西，而不是常规返回。

已针对此部分修改
![image](https://user-images.githubusercontent.com/101685021/200758655-d7403a3a-dd3c-41b1-b57f-95be0333f690.png)

2022-11-09 06:54 UTC, LNSSPsd requested changes
Please format it like that

2022-11-09 06:54 UTC, LNSSPsd commented on doc/script_engine_cn/游戏.md
> +* *`message` `<string>`
```suggestion
  * `message` `<string>`
```

2022-11-09 06:54 UTC, LNSSPsd commented on doc/script_engine_cn/游戏.md
> +*返回值: `<Function>`     取消订阅数据包的功能
```suggestion
* 返回值: `<Function>`     取消订阅数据包的功能
```

2022-11-11 15:10 UTC, Inotart commented
> 

已修改

2022-11-12 12:15 UTC, Torrekie requested changes

2022-11-12 19:30 UTC, Inotart commented on doc/script_engine_cn/文件系统.md
> +* 返回值: `<Boolean>` 布尔值指示指定的项是否为目录。
已按照建议修改部分,但部分提出的内容继续依照 Rup 的提议保留,
文件系统.md的所涉及到的部分,已增加理解用的注释

2022-11-12 21:26 UTC, Torrekie approved these changes
now it looks better

2022-11-13 00:53 UTC, LNSSPsd requested changes

2022-11-13 00:53 UTC, LNSSPsd commented on doc/script_engine_cn/游戏.md
> +* *`name` `<string>`
```suggestion
  * `name` `<string>`
```

2022-11-13 00:53 UTC, LNSSPsd commented on doc/script_engine_cn/游戏.md
> +* *`packet` `<Object>`
```suggestion
  * `packet` `<Object>`
```

2022-11-13 00:53 UTC, LNSSPsd commented on doc/script_engine_cn/常量.md
> +* *`entrypoint` `<string>`
^

2022-11-13 00:53 UTC, LNSSPsd commented on doc/script_engine_cn/常量.md
> +* *`entrypoint` `<string>`
Invalid formats above

2022-11-13 05:35 UTC, Inotart commented on doc/script_engine_cn/常量.md
> +* *`entrypoint` `<string>`
已按照要求修改,但渲染效果 bug 与 FB原文档 的保持一致
![image](https://user-images.githubusercontent.com/101685021/201507527-a3166127-b964-4cee-b5a5-8325e963eb6b.png)

2022-11-13 06:00 UTC, LNSSPsd approved these changes

2022-11-13 06:00 UTC, LNSSPsd commented on doc/script_engine_cn/游戏.md
> +  *`response` `<Object>`
```suggestion
  * `response` `<Object>`
```

2022-11-13 06:05 UTC, merged