Provide Github Release download source support for Termux platform
LNSSPsd/PhoenixBuilder pull request #118
Opened 2022-11-09 08:04 UTC by WillowSauceR

Preview: 
![preview](https://user-images.githubusercontent.com/63277109/200773263-e87061ba-5a54-4288-b25c-29bc39082524.png)

2022-11-09 15:56 UTC, WillowSauceR commented
Preview screenshot of Ubuntu 22.04 platform(Powered by YsCloud docker):
![OtherPlatformPreview](https://user-images.githubusercontent.com/63277109/200877240-e86f5249-33ad-4cde-8434-c6eb706245af.png)

2022-11-11 06:02 UTC, Torrekie commented
We provided an installation guide like this
```bash
bash -c "$(curl -fsSL https://storage.fastbuilder.pro/install.sh)"
```

In that scene, shell script was executed as literal, that means `argv` might not as expected as how we detect it oftentimes. Thus we choose to use environment variables to control some processes of this script (e.g. `LOCAL`)

2022-11-11 14:24 UTC, WillowSauceR commented
> We provided an installation guide like this
> 
> ```shell
> bash -c "$(curl -fsSL https://storage.fastbuilder.pro/install.sh)"
> ```
> 
> In that scene, shell script was executed as literal, that means `argv` might not as expected as how we detect it oftentimes. Thus we choose to use environment variables to control some processes of this script (e.g. `LOCAL`)
Corresponding revisions have been completed:
![屏幕截图_20221111_221707](https://user-images.githubusercontent.com/63277109/201359579-f39aaa72-aa89-40a7-a82e-4b198d14f33c.png)

2022-11-12 12:14 UTC, Torrekie requested changes

2022-11-12 18:03 UTC, LNSSPsd reviewed
Just a suggestion, changes not requested, it's not mandatory to do like that.

2022-11-12 18:03 UTC, LNSSPsd commented on install.sh
> +  printf "\033[33mIf the download is too slow, you can press \"Ctrl+C\" to end the current script and later try to use \"export PB_USE_GH_REPO=1\" and then re-run the installation command to switch t
```suggestion
  printf "\033[33mIf the official storage does not work for you, you can try to assign environment variable \"PB_USE_GH_REPO=1\" for the script to download stuff from Github.\033[0m\n"
```

2022-11-12 18:03 UTC, LNSSPsd commented on install.sh
> +  printf "\033[33mIf the download is too slow, you can press \"Ctrl+C\" to end the current script and later try to use \"export PB_USE_GH_REPO=1\" and then re-run the installation command to switch t
See the suggested change above.

2022-11-12 21:34 UTC, Torrekie approved these changes

2022-11-13 06:18 UTC, LNSSPsd approved these changes

2022-11-13 06:22 UTC, merged