能力管理组件
LNSSPsd/PhoenixBuilder pull request #142
Opened 2022-12-11 09:43 UTC by Liliya233

新的第三方Omega组件，根据玩家拥有的tags对以下能力进行管理（需要OP权限）：
1. 关闭碰撞
2. 开启飞行
3. 操作员命令
4. 禁止使用传送
5. 禁止使用门与开关
6. 禁止发言
7. 禁止打开容器
8. 禁止攻击玩家
9. 禁止攻击生物
10. 禁止放置方块
11. 禁止破坏方块

**我担心以下能力的设置可能会造成不好的后果，所以请慎重考虑后再决定是否通过此PR**
1. 关闭碰撞 - 将允许玩家穿墙
2. 开启飞行 - 将允许非创造玩家进行飞行
3. 操作员命令 - 使用不当可能会造成严重后果

2022-12-11 20:08 UTC, LNSSPsd requested changes

2022-12-11 20:08 UTC, LNSSPsd commented on minecraft/protocol/packet/adventure_settings.go
> +	ActionPermissionUnknow
```suggestion
	ActionPermissionUnknown
```

2022-12-12 01:21 UTC, Liliya233 commented on minecraft/protocol/packet/adventure_settings.go
> +	ActionPermissionUnknow
已更正

2022-12-12 04:29 UTC, LNSSPsd approved these changes

2022-12-12 21:18 UTC, merged