优化README.md
LNSSPsd/PhoenixBuilder pull request #183
Opened 2023-01-12 02:06 UTC by RainyHallways

优化ReadMe并添加双语支持

2023-01-12 03:29 UTC, LNSSPsd requested changes

2023-01-12 03:29 UTC, LNSSPsd commented on README.md
> +PhoenixBuilder is a multifunctional structure generating tool based on gophertunnel which is for the Bedrock Edition of Minecraft (which forked by NetEase).
The main target is weakened, and decorative part of sentence became the object.
This sentence is describing PhoenixBuilder, but turned to describe gophertunnel, and finally MCBE.

2023-01-12 03:29 UTC, LNSSPsd commented on README.md
> +[Here's the Offical Website](https://fastbuilder.pro)
```suggestion
```
It's better to avoid describing non-free(/open source) stuff.

2023-01-12 03:29 UTC, LNSSPsd commented on README.md
> +If your device is Linux-based, you should use Ubuntu 22.04 or you'll meet runtime error.
```suggestion
Note: Those prebuilt binaries require a relatively high `libc6` version.
```

2023-01-12 03:29 UTC, LNSSPsd commented on README.md
> +You can download the newest Release for your device [here](https://github.com/LNSSPsd/PhoenixBuilder/releases) to use it.
```suggestion
Prebuilt binaries available in the Releases tab
```

2023-01-12 03:29 UTC, LNSSPsd commented on README.md
> +Linux platforms Install/Update sh command(This command also applicable for other *nix platforms (iOS, macOS, Android, etc.).):
```suggestion
```

2023-01-12 03:29 UTC, LNSSPsd commented on README.md
> +
Better to avoid using install script as it may pollute/mess up the system environment.

2023-01-12 03:29 UTC, LNSSPsd commented on README.zh-CN.md
> +PhoenixBuilder 是一个基于 gophertunnel 的《Minecraft:基岩版》（由网易代理）多功能结构生成工具。
Minecraft 基岩版不由网易代理。主语过大。

2023-01-12 03:35 UTC, WillowSauceR commented
感觉可以在ZH/EN的开头上都加一个按钮，如下所示
[简体中文](README.zh-CN.md) | [README.md](English)

2023-01-12 03:52 UTC, Torrekie requested changes
please review those suggestions

2023-01-12 03:52 UTC, Torrekie commented on README.zh-CN.md
> +PhoenixBuilder 是一个基于 gophertunnel 的多功能 Minecraft 中国版 结构生成工具。
```suggestion
PhoenixBuilder 是一个基于 gophertunnel 的《我的世界》多功能结构生成工具。
```

2023-01-12 04:03 UTC, RainyHallways commented
> 感觉可以在ZH/EN的开头上都加一个按钮，如下所示 [简体中文](README.zh-CN.md) | [English](README.md)

已修改

2023-01-12 04:08 UTC, Torrekie requested changes

2023-01-12 04:08 UTC, Torrekie commented on README.md
> +If your device is Linux-based, you should use Ubuntu 22.04.Because that those prebuilt binaries require a relatively high `Libc6` version.
```suggestion
If your environment is Linux-based, you may want to use a newer GLibc since our prebuilt binaries for Linux was built on Ubuntu 22.
Or, you can clone this repository and build on your device.
```

2023-01-12 04:08 UTC, Torrekie commented on README.zh-CN.md
> +如果您的设备基于Linux则推荐使用Ubuntu22.04，预构建的文件需要相对较高的`libc6`版本
```suggestion
如果您的运行环境基于Linux，则推荐使用较高版本的Glibc，这是因为预构建是在Ubuntu 22上完成的。
或者，您可以选择在您的本地环境下编译本源码。
```

2023-01-12 04:34 UTC, Torrekie approved these changes

2023-01-12 04:40 UTC, RainyHallways commented
- [x] 内容优化
- [x] 多语言
- [x] 语言选项卡
- [x] 视觉优化

2023-01-12 06:32 UTC, LNSSPsd approved these changes

2023-01-13 05:54 UTC, RainyHallways commented
是现在这版 (可以在语言选项卡和PhoenixBuilder中间加Banner或者Icon) 好还是原来的那版好？（

2023-01-14 07:32 UTC, merged