创建issue反馈模板
LNSSPsd/PhoenixBuilder pull request #186
Opened 2023-01-12 06:57 UTC by RainyHallways

创建issue反馈模板,可在[此处](https://github.com/RainyHallways/ifc/issues/new?assignees=&labels=&template=def.yml)查看效果

2023-01-12 06:58 UTC, RainyHallways commented
附:能够自动添加标签

2023-01-12 07:37 UTC, Torrekie requested changes

2023-01-12 07:37 UTC, Torrekie commented on .github/ISSUE_TEMPLATE/def.yml
> +    - label: "我已在 [Issues 页面](https://github.com/LNSSPsd/PhoenixBuilder/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。"
```suggestion
    - label: "我已在 [Issues 页面](https://github.com/LNSSPsd/PhoenixBuilder/issues?q=is%3Aissue+) 中搜索，确认了在已激活的议题中这一 Bug 未被提及过。"
```

2023-01-12 07:37 UTC, Torrekie commented on .github/ISSUE_TEMPLATE/def.yml
> +    description: "上传其余附件"
```suggestion
    description: "上传其余附件（运行日志等）"
```

2023-01-12 10:28 UTC, Torrekie approved these changes

2023-01-14 19:58 UTC, LNSSPsd commented
Issues are human-reviewed, and maybe it's better to give more freedom in format.

2023-01-15 02:06 UTC, closed without merging