New language: Esperanto
LNSSPsd/PhoenixBuilder pull request #262
Opened 2023-03-03 11:54 UTC by babynanxi

New language: Esperanto
There may be a problem with some syntax

2023-03-04 09:40 UTC, LNSSPsd commented
Improvements might be needed as it couldn't pass ChatGPT's translation quality test.
Here's the detail:
```
The quality of the translation appears to be average. Some of the translations are accurate and convey the intended meaning, while others are not as clear or contain grammar errors. The use of Esperanto appears to be inconsistent and may be confusing for some users. It is recommended to review and improve the translations for clarity and consistency.
```
`- Can you give some examples on inappropriate translations?`
```
Sure! Here are a few examples of translations that could use improvement:

ACME_FailedToGetCommand: "Malsukcesis ricevi acme komandon." This translation is grammatically correct but could be more clear. A better translation might be: "La akme komando malsukcesis esti ricevita."
Auth_InvalidFBVersion: "Nevalida FastBuilder-versio, bonvolu ĝisdatigi." The use of Esperanto here is inconsistent with the rest of the translations and may be confusing for some users. A better translation might be: "Nevalida versio de FastBuilder, bonvolu ĝisdatigi."
Auth_ServerNotFound: "Servilo ne trovita, bonvolu kontroli la publikan staton de via servilo" This translation contains a grammar error and could be more clear. A better translation might be: "La servilo ne estas trovita, bonvolu kontroli la publikan staton de via servilo."
These are just a few examples, and there may be other translations in the text that could use improvement as well.
```

However, what a language model says couldn't always be seen as truth, you can insist on that yours is better and this is only for a reference.

2023-03-04 10:11 UTC, Torrekie commented
we need to find somebody who learned this language hmm

2023-03-04 14:16 UTC, babynanxi commented
I'm getting dizzy. Although Esperanto is relatively simple, I can't

2023-03-07 14:42 UTC, SuperScript-PRC commented
Oh，这是南希写的啊..？

2023-03-08 08:14 UTC, babynanxi commented
I reviewed it three times and personally I am sure that there is no problem, please do the quality test again

2023-03-08 08:21 UTC, Torrekie commented on fastbuilder/i18n/i18n.go
> +	LanguageEsperanto          = "epo"
```suggestion
	LanguageEsperanto          = "eo"
```

2023-03-08 08:21 UTC, Torrekie commented on fastbuilder/i18n/i18n.go
> +	LanguageEsperanto:          I18nDict_epo,
```suggestion
	LanguageEsperanto:          I18nDict_eo,
```

2023-03-08 08:23 UTC, Torrekie requested changes
According to the *nix locale system, Esperanto should be `eo` but not `epo`

Remember rename epo.go to eo.go

2023-03-08 08:29 UTC, babynanxi commented
OK

2023-03-13 01:31 UTC, LNSSPsd commented
Please keep constant strings (arguments) constant.
For an instance, the building option `discrete` should be `discrete` among all the languages,
here's what in your translation:
`DelayThreshold_OnlyDiscrete: "Prokrasta sojlo disponeblas nur kun prokrasta reĝimo: diskreta",`
Users have no way to access that option by giving `diskreta`.

2023-03-13 13:20 UTC, babynanxi commented
sorry wrong operation

2023-03-13 15:19 UTC, LNSSPsd commented
Here's what in your updated version:
```
DelayThreshold_OnlyDiscrete: "Prokrastsojlo disponeblas nur kun prokrasta reĝimo: disperso",
```
However, possible options for delay threshold are only `continuous`, `discrete` or `none`, `disperso` isn't going to be one, so it's better to keep it constant.

2023-03-14 13:31 UTC, babynanxi commented
Is "discrete" a value?

2023-03-16 04:35 UTC, LNSSPsd commented
> Is "discrete" a value?

It's an enum value.

2023-03-18 07:54 UTC, babynanxi commented
Restore the enum value

2023-03-19 02:21 UTC, LNSSPsd commented
And DelaySetUnavailableUnderNoneMode, etc.

2023-03-22 04:15 UTC, LNSSPsd commented
Some more problems figured out by ChatGPT:
```
Based on my assessment of the translation, there are a few errors that need to be addressed. Here's a breakdown of the errors:

    The word "Enter" has been translated as "Enigu", which is not a correct translation. A better translation for "Enter" in this context would be "Enmetu".
    The word "Password" has been translated as "Pasvorton", which is correct, although it could also be translated as "Pasvorto" without changing the meaning significantly.
    The phrase "Press [Enter]" has been translated as "Premu [Enigu]", which is not a correct translation. A better translation for "Press [Enter]" in this context would be "Premu [Enmetu]".
    The phrase "if not set" has been translated as "se ne agordita", which is not a correct translation. A better translation for "if not set" in this context would be "se ne difinita".
    The phrase "input won't be echoed" has been translated as "enigo ne estos ripetita", which is not a correct translation. A better translation for "input won't be echoed" in this context would be "eniga teksto ne estos montrita".

Overall, I would give the translation a score of 60 out of 100, as there are several errors in the translation that could cause confusion for the reader. A more accurate translation could be: "Enmetu Pasvorton (Premu [Enmetu] se ne difinita, eniga teksto ne estos montrita):".
```

2023-04-01 15:31 UTC, shwodbowhsjdk commented
为什么你们用英文交流啊，不都要翻译回来吗What are you pretending to be, man

2023-04-01 15:45 UTC, Happy2018new commented
> 为什么你们用英文交流啊，不都要翻译回来吗What are you pretending to be, man

习惯吧

2023-04-01 21:49 UTC, SuperScript-PRC commented
>  为什么你们用英文交流啊，不都要翻译回来吗What are you pretending to be, man
因为here's github

2023-04-11 16:09 UTC, Inotart commented
草

2023-04-11 16:11 UTC, babynanxi commented
> 

？

2023-04-11 16:11 UTC, Inotart commented
你好,我目前不在，如果你只是看到论坛邮件就不用回复了

2023-04-30 16:16 UTC, closed without merging