轻量化lua插件支持
LNSSPsd/PhoenixBuilder pull request #294
Opened 2023-06-20 18:11 UTC by awaqwqa

完成了安全的文件操作
全体插件工作目录为/data/lua下
插件实现为:/data/lua/ 配置为:/data/lua/config
实现了命令操作 也就是通过后台输入 lua luas help就可以知道各种关于插件的指令操作 包括:新建立插件 删除插件 重载插件等等
实现了lua代码报错提示 方便调试
接口部分实现了getgamecontrol的代码 现在处于能发指令 和有返回值的指令
getlisten()   todo 因为有点打脑壳

2023-06-21 02:06 UTC, CMA2401PT commented
我想在正式提交之前，我们还有一些工作要做，目的是为了避免陷入之前python那种多级配置（在omega side下配置python插件），即然我们已经调整了主框架，那么，我们可以做的更彻底一点。例如，在正常的配置中，将Source从Built-In改为Lua，并将配置转向对应的lua文件。这样，让lua插件“看起来”和omega内置插件平行

2023-06-21 03:55 UTC, awaqwqa commented
行！

2023-06-21 04:02 UTC, awaqwqa commented
那就是流程改变一下:默认不具备无lua插件然后通过lua luas new创建时创建一个配置文件 然后逻辑实现部分也一并写在这个目录之下吗 列如配置/lua1号插件.json 配置/lua1号插件.lua
然后在读取omg读取到这个Lua配置文件时丢给处理中心处理 还是说读取到时不做处理 然后等待lua插件支持组件来处理 实现起来效果应该是差不多的

2023-06-21 05:07 UTC, CMA2401PT commented
让对应的lua处理，简单来说，就是看起来/使用起来和普通的内置插件别无二致（除了Source不一样而已），而不是omega side 那样在side下配置，嗯，就是拔高一层

2023-06-22 14:53 UTC, awaqwqa commented
（加载提示部分有点奇怪 后面应该修改一下插件config的去向管理 
然后应该大致符合要求了 就是后面疯狂加api（内置函数

2023-06-23 03:04 UTC, awaqwqa commented
好了 加载提示一样了（

2023-06-23 03:38 UTC, CMA2401PT commented
感觉可以合并了，不过可以先默认关闭它，因为我们还需要一点时间考虑兼容性（对未来可能的变化的兼容）和其可能造成的负面影响，以及接口是否优雅。这些工作可以在合并之后进行

2023-06-23 03:45 UTC, awaqwqa commented
可能还要稍作修改 就是在用指令新建指令后 lua代码用含有教程的注释初始化

2023-06-23 03:56 UTC, awaqwqa commented
还有就是 lua插件指出组件我是塞进core组件的（） 然后就没办法关闭 但是每次新建lua组件都是默认关闭 并且有lua luas delect可以让玩家删除组件（）下午我添加一下lua代码的初始化注释（

2023-06-23 04:14 UTC, Happy2018new commented
合并前先把上述已发现的单词拼写问题解决一下吧。

2023-06-23 05:21 UTC, CMA2401PT commented
另外，希望能把主要部分移动到 mainframe/lang_support/lua_frame 下，就是新建一个文件夹，这样有助于厘清各个功能间的层次关系

2023-06-23 06:47 UTC, RainyHallways requested changes
请查看以下语言本地化建议

2023-06-23 06:47 UTC, RainyHallways commented on omega/mainframe/default_components.json
> +    "是否禁用": false,
默认为禁用是不是更好？（

2023-06-23 06:47 UTC, RainyHallways commented on omega/mainframe/luaMonitor.go
> +		errors.New(fmt.Sprintf("你正在尝试运行组件:%v 但是它并未在配置文件之中找到 请确定它存在", name))
请确定它存在→请确定它是否存在？

2023-06-23 06:47 UTC, RainyHallways commented on omega/mainframe/luaMonitor.go
> +		return errors.New(fmt.Sprintf("很显然%v并不是指令的任何一种 请输入lua luas help寻求帮助", msg))
很显然%v并不是指令的任何一种→很显然%v并不包含于任意指令集？

2023-06-23 06:47 UTC, RainyHallways commented on omega/mainframe/luaMonitor.go
> +			return errors.New("lua reload compoent指令后面应该有且仅有一个参数")
lua reload compoent指令后面应该有且仅有一个参数→lua reload compoent指令后应只包含一个参数?

2023-06-23 06:47 UTC, RainyHallways commented on omega/mainframe/luaMonitor.go
> +			return errors.New(fmt.Sprintf("你正在尝试运行组件:%v 但是它并未在配置文件之中找到 请确定它存在", componentName))
是否存在?

2023-06-23 06:47 UTC, RainyHallways commented on omega/mainframe/luaMonitor.go
> +		PrintInfo(NewPrintMsg("提示", fmt.Sprintf("%v已经重新加载", componentName)))
%v已经重新加载→已经重新加载%v组件？

2023-06-23 06:47 UTC, RainyHallways commented on omega/mainframe/luaMonitor.go
> +		return errors.New(fmt.Sprintf("你正在尝试运行组件:%v 但是它并未在配置文件之中找到 请确定它存在", name))
是否存在？

2023-06-23 06:47 UTC, RainyHallways commented on omega/mainframe/luaMonitor.go
> +			PrintInfo(NewPrintMsg("lua插件", fmt.Sprintf("%v插件启动成功 版本:%v", Name, m.ComponentPoll[Name].Config.Version)))
%v插件启动成功 版本:%v→插件%v|Ver:%v 启动成功?

2023-06-23 06:47 UTC, RainyHallways commented on omega/mainframe/luaMonitor.go
> +		PrintInfo(NewPrintMsg("提示", fmt.Sprintf("已经创建文件基本结构请到目录%v 修改", OMGCONFIGPATH+SEPA+componentName)))
已经创建文件基本结构，请至目录%v 修改

2023-06-23 06:47 UTC, RainyHallways commented on omega/mainframe/luaMonitor.go
> +			return errors.New(fmt.Sprintf("我们并没有在加载的插件池子中找到%v", name))
我们并未在加载的插件池中找到%v

2023-06-23 06:47 UTC, RainyHallways commented on omega/mainframe/luaUtils.go
> +	PrintInfo(NewPrintMsg("提示", fmt.Sprintf("%v已经删除 干净了", name)))
？

2023-06-23 06:47 UTC, RainyHallways commented on omega/mainframe/luaUtils.go
> +		return errors.New("该名字的lua组件已经存在")
该lua组件已经存在？

2023-06-23 06:47 UTC, RainyHallways commented on omega/mainframe/luaMonitor.go
> +		return errors.New("未知指令 请输入lua luas help寻求帮助")
寻求→获得？

2023-06-23 06:47 UTC, RainyHallways commented on omega/mainframe/luaMonitor.go
> +			errors.New(fmt.Sprintf("找到了%v插件配置文件 但是配置文件处于关闭状态", name))
找到了%v插件的配置文件 但此组件处于关闭状态

2023-06-23 07:17 UTC, awaqwqa commented on omega/mainframe/default_components.json
> +    "是否禁用": false,
core组件默认关闭就报错（改为lua组件就行了

2023-06-23 07:28 UTC, awaqwqa commented
太生草了

2023-06-23 11:10 UTC, CMA2401PT commented on omega/mainframe/luaMonitor.go
> +			errors.New(fmt.Sprintf("找到了%v插件配置文件 但是配置文件处于关闭状态", name))
发的很好，下次别在这发了，这种都称不上问题的细节可以先放一放，太占地儿了

2023-06-23 11:14 UTC, RainyHallways commented
本来想hide的（
找不到在哪（



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年06月23日 19:10 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [LNSSPsd/PhoenixBuilder] 轻量化lua插件支持 (PR #294) |

@CMA2401PT commented on this pull request.

In omega/mainframe/luaMonitor.go:

> +		_config := v.jsonConfig
+		//如果配置文件是开启
+		if !_config.Disabled {
+			L := lua.NewState()
+			// 为 Lua 虚拟机提供一个安全的环境 提供基础的方法
+			if err := m.BuiltlnFner.LoadFn(L); err != nil {
+				return err
+			}
+			m.ComponentPoll[k] = &LuaComponent{
+				L:       L,
+				Msg:     make(map[string]string),
+				Running: false, //初始化完成但是未运行
+				Config:  _config,
+			}
+		} else {
+			errors.New(fmt.Sprintf("找到了%v插件配置文件 但是配置文件处于关闭状态", name))


发的很好，下次别在这发了，这种都称不上问题的细节可以先放一放，太占地儿了

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***>

2023-06-24 12:55 UTC, Torrekie commented
Something to notice:
- Lua was maintained terribly by upstream, I would prefer languages like Perl or Ruby that has already been embedded/provided by vendors or systems so that users could avoid installing additional dependencies (Same for Lua, make sure your stuff is calling system Lua)
- We already have a V8 based JavaScript engine that providing functionality of loading custom js extensions, is there any necessity to add another?
- For current stage I think there should have a huge reconstruction of the feature of loading extensions, I would prefer ways like other programs that implement language extensions by compiling itself to target languages' module (e.g. PHP can compile itself to a shared object that used by Apache2/httpd) so adding new engines is still arguing.

2023-06-24 13:55 UTC, CMA2401PT commented
> 

lua 在游戏许多游戏中被广泛用作脚本语言。lua设计目标就是一个轻量化的脚本语言，这点使其远远比其他语言更有资格。至今为止，fb的readline造成的各种兼容性问题来看（思考一下，没有readline的情况下，fb可以直接跑在一个啥都没有的busybox上，而为了用上“系统的”readline，居然要做这么多工作，而且还不支持windows），要我说，想依赖这个，依赖那个就别用go，go语言好不容易消除库文件的概念，把所有的东西编到一个可执行文件中，现在居然要开倒车，好好的没事非得依赖一个库简直是自讨苦吃。
V8这玩意占了30多MB，fb本身也才十几MB，用户的小水管下的动么，但这些都不关键，至今没有V8版windows fb，如果这都不算问题，自从js引擎从otto换成V8之后，js开发者都无法debug调试脚本
关于最后一点，go没法使用插件，只有linux底下有一些黑魔法可以做到

但凡写过一点插件，就能明白问题的痛点如下：
1. 用户需要写自己的插件/功能脚本（可以但不是必须的是，这个脚本的语言要好上手）
2. 对这个脚本的支持最好要跨平台，如果这个支持可以和fb一起编译再好不过，省的为每个平台还得拖泥带水的写一堆适配代码，弄一堆库或者依赖（对，说起这个来，你之前众筹买平板时还提到要为omega的cqhttp和python提供ios支持呢）
3. 想跑这个插件最好不要搞的太复杂，便于开发的人快速上手尝试和试错，环节多了更容易出问题
再没有比lua更好的选择了

2023-06-24 17:18 UTC, awaqwqa commented
完成文件集体移动了 修改了部分lua交互的逻辑 改为了堵塞式让操作更加无脑
初始化文件后会在lua代码里面加上一段使用说明

2023-06-24 18:28 UTC, Happy2018new requested changes
其中有关 `blockNBT_API` 的部分已经被重名并且迁移，且也不再为 `Omega` 提供，因此为确保可以编译通过，请从接口中删除它们。

2023-06-24 18:28 UTC, Happy2018new commented on omega/mainframe/lang_support/lua_frame/omgcomponentapi/omgimpl.go
> +	GetNewUQHolder() *blockNBT_API.PacketHandleResult
```suggestion

```

此 `API` 已重名且不再为  `Omega` 提供。

2023-06-24 18:28 UTC, Happy2018new commented on omega/mainframe/lang_support/lua_frame/omgcomponentapi/omgimpl.go
> +	blockNBT_API "phoenixbuilder/fastbuilder/bdump/blockNBT/API"
```suggestion

```
此 `API` 已重名且不再为 `Omega` 提供。

2023-06-24 23:08 UTC, awaqwqa commented
奇怪（）我等会儿把它给删掉

2023-06-25 09:30 UTC, Torrekie commented
> lua 在游戏许多游戏中被广泛用作脚本语言。lua设计目标就是一个轻量化的脚本语言，这点使其远远比其他语言更有资格。至今为止，fb的readline造成的各种兼容性问题来看（思考一下，没有readline的情况下，fb可以直接跑在一个啥都没有的busybox上，而为了用上“系统的”readline，居然要做这么多工作，而且还不支持windows），要我说，想依赖这个，依赖那个就别用go，go语言好不容易消除库文件的概念，把所有的东西编到一个可执行文件中，现在居然要开倒车，好好的没事非得依赖一个库简直是自讨苦吃。 V8这玩意占了30多MB，fb本身也才十几MB，用户的小水管下的动么，但这些都不关键，至今没有V8版windows fb，如果这都不算问题，自从js引擎从otto换成V8之后，js开发者都无法debug调试脚本 关于最后一点，go没法使用插件，只有linux底下有一些黑魔法可以做到
> 
> 但凡写过一点插件，就能明白问题的痛点如下：
> 
> 1. 用户需要写自己的插件/功能脚本（可以但不是必须的是，这个脚本的语言要好上手）

JavaScript and V8 was absolutely compatible with most common platforms (at least Windows and Linux), the linkage for `readline` and maybe `ncurses` is to support vendor terminal environment even though PhoenixBuilder can be built with a static libreadline. Yes I agree we need more considerations for Windows users as they uses completely different terminal structure. This is absolutely going to be added to the TODO list.

> 2. 对这个脚本的支持最好要跨平台，如果这个支持可以和fb一起编译再好不过，省的为每个平台还得拖泥带水的写一堆适配代码，弄一堆库或者依赖（对，说起这个来，你之前众筹买平板时还提到要为omega的cqhttp和python提供ios支持呢）

Vendors is providing FOSS with heavily maintained patches/releasing processes based on system characteristics, they do most considerations on security and compatibility, that's why we always need *software repositories* on *nix systems. For that reason I am maintaining an iOS APT repo (Currently opened [patches](https://github.com/Torrekie/apt.torrekie.com-patches) I applied for projects, the maintainer processes will be opened soon when I done everything) for the preparation of full Omega features portage, Golang is absolutely planned.

Golang is still building with vendor C API, Golang devs avoided configuration processes by explicitly specifying platform APIs and features. This do ensured the stability of Go running on predefined platforms but the shortage is still obvious: only limited system C features is supported on common platforms and iOS or some *nix distros/archs is absolutely not considered, that's why we always need vendors to do those bunch of stuff to make sure what you writes can works on their platforms.

PhoenixBuilder is not provided/maintained by any distro, so that for our users to have the best stability, we should always provide platform compatible codes. What you suggests does not avoiding dependencies at all, they does not disappears but transformed to our pressure on main executable.

> 3. 想跑这个插件最好不要搞的太复杂，便于开发的人快速上手尝试和试错，环节多了更容易出问题

Still the reason of "vendor maintaining" that I mentioned above, Lua is light-weight I agree but still been provided by system vendor. By inspecting the latest [lua5.4](https://salsa.debian.org/lua-team/lua5.4) maintained by Debian Lua Team you can still see CVE vulnerabilities patches, so how we make sure we can build Lua correctly and not introducing any bugs for every platforms? 

>    再没有比lua更好的选择了

System one is always the best one, they are more professional than us.


Btw, which Lua implementations we are going to use? Lua or LuaJIT? I believe LuaJIT has better performance than the standard Lua but it is not synced with upstream which means the Lua version provided by LuaJIT is not the latest one, which increases the risk of affected by vulnerabilities. How do you make the choice? Stability or efficiency?

2023-06-25 10:38 UTC, CMA2401PT commented
也许，在未来这一切问题都会被解决，我们能得到一个非常完美的，轻、快、跨平台、可以debug等等各方面很完善的js解释器。但是这要花多少时间呢？又得等多久呢？如果我们立即行动起来，投入到js引擎的开发中，比如魔改V8之类的，会不会跑的有点远？又需要多长时间才能完成？比较理想的js引擎是fastjs，但是，它同样没有jit，大家都知道，添加jit支持绝非易事。

事实上，无论是第一版的otto，还是后来的 v8，我花了相当多的时间在上面，里面相当部分也是由我写的，要论放弃V8，我肯定是最不情愿的人之一。但是，在面对将V8嵌入js的种种问题时，我们无法在短时间，甚至是很长时间内解决这些问题。这并不是说我们没有努力尝试过解决这些问题，而是，在相当久的努力之后，结论就是，即使花上很长时间也无法克服这些问题。

现在必须要做出选择了，也许是做出折衷？说实在的，这种事情在编程里还挺经常发生的。我们到底是选择，很强大但是问题很多，而且这些问题还是很难修正的东西；还是一个不那么强大，但是相对来说更容易控制和使用的东西呢？我们已经在插件实现的道路上尝试了种种可能性：直接制作模块让linuxfb加载；使用网络通信；链接其他语言的解释器；直接将功能硬编码。我想我们应该从中吸取经验和教训

而且，话说回来，lua到底差在哪里呢？很多程序都选择嵌入lua作为它们的脚本语言，它天生就是干这个的。如果你担心的是，它不像js那样强大，那么想一想neovim吧，这个新时代的vim同样选择了lua作为它们的脚本语言和插件语言，甚至用它实现lsp也毫无问题。

至于你提到的究竟使用那个lua解释器，我们并不打算用luajit，虽然那个性能更强，我们打算使用的是一个用go语言编写的lua解释器，所以你提到的CVE并不适用它。而且，即时有漏洞也不是问题，它不是作为一个服务端出现的角色，它是运行在客户端里的脚本解释器，其运行的脚本肯定是用户选择的，不存在在用户不知情的情况下，从网络上注入一个恶意lua脚本这种情况，如果有，那也是用户先运行了一个恶意脚本。

2023-06-25 13:59 UTC, Happy2018new approved these changes
仅针对（我）已发现的注释错误、拼写问题等所作出的批准，因为它们现在已被全部解决。

2023-06-25 15:26 UTC, RainyHallways approved these changes

2023-06-25 18:38 UTC, LNSSPsd approved these changes

2023-06-25 18:39 UTC, merged